import {
  FormControl,
  Input,
  Icon,
  Checkbox,
  WarningOutlineIcon,
  Alert,
  Box,
  IconButton,
  Slide,
  Column,
  Row,
  Container,
  Badge,
  Heading,
  TextArea,
  Avatar,
  Select,
  Switch,
  Radio,
  View,
  Popover,
  Button,
  NativeBaseProvider,
  Spinner,
  Divider,
  Actionsheet,
} from "native-base";
import { useEffect, useState, memo, useCallback, useMemo } from "react";
import {
  TouchableOpacity,
  LogBox,
  Text,
  Image,
  SafeAreaView,
  Modal,
  ScrollView,
  StatusBar,
  ImageBackground,
  FlatList,
  TouchableWithoutFeedback,
  TextInput,
  useWindowDimensions,
  Keyboard,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  StyleSheet,
} from "react-native";
import { useForm, Controller } from "react-hook-form";
import * as yup from "yup";
import { yupResolver } from "@hookform/resolvers/yup";

import { useDispatch, useSelector } from "react-redux";

import Toast from "react-native-toast-message";

import LinearGradient from "react-native-linear-gradient";

export default {
  Keyboard,
  KeyboardAvoidingView,
  LinearGradient,
  Platform,
  memo,
  useCallback,
  useMemo,
  Modal,
  Divider,
  TextInput,
  FormControl,
  Input,
  Icon,
  TouchableOpacity,
  Checkbox,
  useEffect,
  useState,
  LogBox,
  WarningOutlineIcon,
  useForm,
  Controller,
  yup,
  yupResolver,
  Alert,
  Box,
  Text,
  View,
  Image,
  IconButton,
  Slide,
  SafeAreaView,
  ScrollView,
  StatusBar,
  Column,
  Row,
  Container,
  Badge,
  ImageBackground,
  Heading,
  FlatList,
  TouchableWithoutFeedback,
  TextArea,
  Avatar,
  Select,
  Switch,
  Actionsheet,
  Radio,
  Popover,
  Button,
  NativeBaseProvider,
  useDispatch,
  Toast,
  Spinner,
  useSelector,
  useWindowDimensions,
  Pressable,
  StyleSheet,
};
